// Code generated by wit-bindgen-go. DO NOT EDIT.

package semver

// Exports represents the caller-defined exports from "jcbhmr:mod/semver@0.36.0".
var Exports struct {
	// Build represents the caller-defined, exported function "build".
	//
	//	build: func(v: string) -> string
	Build func(v string) (result string)

	// Canonical represents the caller-defined, exported function "canonical".
	//
	//	canonical: func(v: string) -> string
	Canonical func(v string) (result string)
}
