// Code generated by wit-bindgen-go. DO NOT EDIT.

package semver

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "jcbhmr:mod@0.36.0".

//go:wasmexport jcbhmr:mod/semver@0.36.0#build
//export jcbhmr:mod/semver@0.36.0#build
func wasmexport_Build(v0 *uint8, v1 uint32) (result *string) {
	v := cm.LiftString[string]((*uint8)(v0), (uint32)(v1))
	result_ := Exports.Build(v)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/semver@0.36.0#canonical
//export jcbhmr:mod/semver@0.36.0#canonical
func wasmexport_Canonical(v0 *uint8, v1 uint32) (result *string) {
	v := cm.LiftString[string]((*uint8)(v0), (uint32)(v1))
	result_ := Exports.Canonical(v)
	result = &result_
	return
}
