// Code generated by wit-bindgen-go. DO NOT EDIT.

package modfile

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "jcbhmr:mod@0.36.0".

//go:wasmexport jcbhmr:mod/modfile@0.36.0#get-go-version-RE
//export jcbhmr:mod/modfile@0.36.0#get-go-version-RE
func wasmexport_GetGoVersionRE() {
	Exports.GetGoVersionRE()
	return
}

//go:wasmexport jcbhmr:mod/modfile@0.36.0#get-toolchain-RE
//export jcbhmr:mod/modfile@0.36.0#get-toolchain-RE
func wasmexport_GetToolchainRE() {
	Exports.GetToolchainRE()
	return
}

//go:wasmexport jcbhmr:mod/modfile@0.36.0#auto-quote
//export jcbhmr:mod/modfile@0.36.0#auto-quote
func wasmexport_AutoQuote(s0 *uint8, s1 uint32) (result *string) {
	s := cm.LiftString[string]((*uint8)(s0), (uint32)(s1))
	result_ := Exports.AutoQuote(s)
	result = &result_
	return
}
