// Code generated by wit-bindgen-go. DO NOT EDIT.

package modfile

// Exports represents the caller-defined exports from "jcbhmr:mod/modfile@0.36.0".
var Exports struct {
	// GetGoVersionRE represents the caller-defined, exported function "get-go-version-RE".
	//
	//	get-go-version-RE: func()
	GetGoVersionRE func()

	// GetToolchainRE represents the caller-defined, exported function "get-toolchain-RE".
	//
	//	get-toolchain-RE: func()
	GetToolchainRE func()

	// AutoQuote represents the caller-defined, exported function "auto-quote".
	//
	//	auto-quote: func(s: string) -> string
	AutoQuote func(s string) (result string)
}
