// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package module represents the exported interface "jcbhmr:mod/module@0.36.0".
package module

import (
	"go.bytecodealliance.org/cm"
)

// Version represents the record "jcbhmr:mod/module@0.36.0#version".
//
//	record version {
//		path: string,
//		version: string,
//	}
type Version struct {
	_       cm.HostLayout `json:"-"`
	Path    string        `json:"path"`
	Version string        `json:"version"`
}
