// Code generated by wit-bindgen-go. DO NOT EDIT.

package module

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "jcbhmr:mod/module@0.36.0".
var Exports struct {
	// InvalidPathError represents the caller-defined exports for resource "jcbhmr:mod/module@0.36.0#invalid-path-error".
	InvalidPathError struct {
		// Destructor represents the caller-defined, exported destructor for resource "invalid-path-error".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// Constructor represents the caller-defined, exported constructor for resource "invalid-path-error".
		//
		//	constructor()
		Constructor func() (result InvalidPathError)

		// Error represents the caller-defined, exported method "error".
		//
		//	error: func() -> string
		Error func(self cm.Rep) (result string)

		// GetErr represents the caller-defined, exported method "get-err".
		//
		//	get-err: func() -> error
		GetErr func(self cm.Rep) (result Error)

		// GetKind represents the caller-defined, exported method "get-kind".
		//
		//	get-kind: func() -> string
		GetKind func(self cm.Rep) (result string)

		// GetPath represents the caller-defined, exported method "get-path".
		//
		//	get-path: func() -> string
		GetPath func(self cm.Rep) (result string)

		// SetKind represents the caller-defined, exported method "set-kind".
		//
		//	set-kind: func(v: string)
		SetKind func(self cm.Rep, v string)

		// SetPath represents the caller-defined, exported method "set-path".
		//
		//	set-path: func(v: string)
		SetPath func(self cm.Rep, v string)

		// Unwrap represents the caller-defined, exported method "unwrap".
		//
		//	unwrap: func() -> error
		Unwrap func(self cm.Rep) (result Error)
	}

	// InvalidVersionError represents the caller-defined exports for resource "jcbhmr:mod/module@0.36.0#invalid-version-error".
	InvalidVersionError struct {
		// Destructor represents the caller-defined, exported destructor for resource "invalid-version-error".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// ExportConstructor represents the caller-defined, exported constructor for resource "invalid-version-error".
		//
		//	constructor()
		ExportConstructor func() (result InvalidVersionError)

		// Error represents the caller-defined, exported method "error".
		//
		//	error: func() -> string
		Error func(self cm.Rep) (result string)

		// GetErr represents the caller-defined, exported method "get-err".
		//
		//	get-err: func() -> error
		GetErr func(self cm.Rep) (result Error)

		// GetPseudo represents the caller-defined, exported method "get-pseudo".
		//
		//	get-pseudo: func() -> bool
		GetPseudo func(self cm.Rep) (result bool)

		// GetVersion represents the caller-defined, exported method "get-version".
		//
		//	get-version: func() -> string
		GetVersion func(self cm.Rep) (result string)

		// SetPseudo represents the caller-defined, exported method "set-pseudo".
		//
		//	set-pseudo: func(v: bool)
		SetPseudo func(self cm.Rep, v bool)

		// SetVersion represents the caller-defined, exported method "set-version".
		//
		//	set-version: func(v: string)
		SetVersion func(self cm.Rep, v string)

		// Unwrap represents the caller-defined, exported method "unwrap".
		//
		//	unwrap: func() -> error
		Unwrap func(self cm.Rep) (result Error)
	}

	// ModuleError represents the caller-defined exports for resource "jcbhmr:mod/module@0.36.0#module-error".
	ModuleError struct {
		// Destructor represents the caller-defined, exported destructor for resource "module-error".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// ExportConstructor_ represents the caller-defined, exported constructor for resource "module-error".
		//
		//	constructor()
		ExportConstructor_ func() (result ModuleError)

		// Error represents the caller-defined, exported method "error".
		//
		//	error: func() -> string
		Error func(self cm.Rep) (result string)

		// GetErr represents the caller-defined, exported method "get-err".
		//
		//	get-err: func() -> error
		GetErr func(self cm.Rep) (result Error)

		// GetPath represents the caller-defined, exported method "get-path".
		//
		//	get-path: func() -> string
		GetPath func(self cm.Rep) (result string)

		// GetVersion represents the caller-defined, exported method "get-version".
		//
		//	get-version: func() -> string
		GetVersion func(self cm.Rep) (result string)

		// SetPath represents the caller-defined, exported method "set-path".
		//
		//	set-path: func(v: string)
		SetPath func(self cm.Rep, v string)

		// SetVersion represents the caller-defined, exported method "set-version".
		//
		//	set-version: func(v: string)
		SetVersion func(self cm.Rep, v string)

		// Unwrap represents the caller-defined, exported method "unwrap".
		//
		//	unwrap: func() -> error
		Unwrap func(self cm.Rep) (result Error)
	}

	// PseudoVersionTimestampFormat represents the caller-defined, exported function "pseudo-version-timestamp-format".
	//
	//	pseudo-version-timestamp-format: func(t: s64) -> string
	PseudoVersionTimestampFormat func(t int64) (result string)

	// CanonicalVersion represents the caller-defined, exported function "canonical-version".
	//
	//	canonical-version: func(v: string) -> string
	CanonicalVersion func(v string) (result string)

	// Check represents the caller-defined, exported function "check".
	//
	//	check: func(path: string, version: string) -> error
	Check func(path string, version string) (result Error)

	// CheckFilePath represents the caller-defined, exported function "check-file-path".
	//
	//	check-file-path: func(path: string) -> error
	CheckFilePath func(path string) (result Error)

	// CheckImportPath represents the caller-defined, exported function "check-import-path".
	//
	//	check-import-path: func(path: string) -> error
	CheckImportPath func(path string) (result Error)

	// CheckPath represents the caller-defined, exported function "check-path".
	//
	//	check-path: func(path: string) -> error
	CheckPath func(path string) (result Error)

	// CheckPathMajor represents the caller-defined, exported function "check-path-major".
	//
	//	check-path-major: func(v: string, path-major: string) -> error
	CheckPathMajor func(v string, pathMajor string) (result Error)

	// EscapePath represents the caller-defined, exported function "escape-path".
	//
	//	escape-path: func(path: string) -> result<string, error>
	EscapePath func(path string) (result cm.Result[string, string, Error])

	// EscapeVersion represents the caller-defined, exported function "escape-version".
	//
	//	escape-version: func(v: string) -> result<string, error>
	EscapeVersion func(v string) (result cm.Result[string, string, Error])

	// IsPseudoVersion represents the caller-defined, exported function "is-pseudo-version".
	//
	//	is-pseudo-version: func(v: string) -> bool
	IsPseudoVersion func(v string) (result bool)

	// IsZeroPseudoVersion represents the caller-defined, exported function "is-zero-pseudo-version".
	//
	//	is-zero-pseudo-version: func(v: string) -> bool
	IsZeroPseudoVersion func(v string) (result bool)

	// MatchPathMajor represents the caller-defined, exported function "match-path-major".
	//
	//	match-path-major: func(v: string, path-major: string) -> bool
	MatchPathMajor func(v string, pathMajor string) (result bool)

	// MatchPrefixPatterns represents the caller-defined, exported function "match-prefix-patterns".
	//
	//	match-prefix-patterns: func(globs: string, target: string) -> bool
	MatchPrefixPatterns func(globs string, target string) (result bool)

	// PathMajorPrefix represents the caller-defined, exported function "path-major-prefix".
	//
	//	path-major-prefix: func(path-major: string) -> string
	PathMajorPrefix func(pathMajor string) (result string)

	// PseudoVersion represents the caller-defined, exported function "pseudo-version".
	//
	//	pseudo-version: func(major: string, older: string, t: s64, rev: string) -> string
	PseudoVersion func(major string, older string, t int64, rev string) (result string)

	// PseudoVersionBase represents the caller-defined, exported function "pseudo-version-base".
	//
	//	pseudo-version-base: func(v: string) -> result<string, error>
	PseudoVersionBase func(v string) (result cm.Result[string, string, Error])

	// PseudoVersionRev represents the caller-defined, exported function "pseudo-version-rev".
	//
	//	pseudo-version-rev: func(v: string) -> result<string, error>
	PseudoVersionRev func(v string) (result cm.Result[string, string, Error])

	// PseudoVersionTime represents the caller-defined, exported function "pseudo-version-time".
	//
	//	pseudo-version-time: func(v: string) -> result<s64, error>
	PseudoVersionTime func(v string) (result cm.Result[string, int64, Error])

	// Sort represents the caller-defined, exported function "sort".
	//
	//	sort: func(%list: list<version>) -> list<version>
	Sort func(list cm.List[Version]) (result cm.List[Version])

	// SplitPathVersion represents the caller-defined, exported function "split-path-version".
	//
	//	split-path-version: func(path: string) -> option<tuple<string, string>>
	SplitPathVersion func(path string) (result cm.Option[[2]string])

	// UnescapePath represents the caller-defined, exported function "unescape-path".
	//
	//	unescape-path: func(escaped: string) -> result<string, error>
	UnescapePath func(escaped string) (result cm.Result[string, string, Error])

	// UnescapeVersion represents the caller-defined, exported function "unescape-version".
	//
	//	unescape-version: func(escaped: string) -> result<string, error>
	UnescapeVersion func(escaped string) (result cm.Result[string, string, Error])

	// VersionError represents the caller-defined, exported function "version-error".
	//
	//	version-error: func(v: version, err: error) -> error
	VersionError func(v Version, err Error) (result Error)

	// ZeroPseudoVersion represents the caller-defined, exported function "zero-pseudo-version".
	//
	//	zero-pseudo-version: func(major: string) -> string
	ZeroPseudoVersion func(major string) (result string)

	// VersionString represents the caller-defined, exported function "version-string".
	//
	//	version-string: func() -> string
	VersionString func(self Version) (result string)
}
