// Code generated by wit-bindgen-go. DO NOT EDIT.

package module

// This file contains wasmimport and wasmexport declarations for "jcbhmr:mod@0.36.0".

//go:wasmexport jcbhmr:mod/module@0.36.0#version-string
//export jcbhmr:mod/module@0.36.0#version-string
func wasmexport_VersionString(self0 *uint8, self1 uint32, self2 *uint8, self3 uint32) (result *string) {
	self := lift_Version((*uint8)(self0), (uint32)(self1), (*uint8)(self2), (uint32)(self3))
	result_ := Exports.VersionString(self)
	result = &result_
	return
}
