// Code generated by wit-bindgen-go. DO NOT EDIT.

package module

// Exports represents the caller-defined exports from "jcbhmr:mod/module@0.36.0".
var Exports struct {
	// VersionString represents the caller-defined, exported function "version-string".
	//
	//	version-string: func() -> string
	VersionString func(self Version) (result string)
}
