// Code generated by wit-bindgen-go. DO NOT EDIT.

package zip

import (
	"go.bytecodealliance.org/cm"
	"go.jcbhmr.com.internal/mod-wasm/internal/jcbhmr/mod/module"
)

func lift_Version(f0 *uint8, f1 uint32, f2 *uint8, f3 uint32) (v module.Version) {
	v.Path = cm.LiftString[string](f0, f1)
	v.Version = cm.LiftString[string](f2, f3)
	return
}

func lift_OptionError(f0 uint32, f1 *uint8, f2 uint32) (v cm.Option[Error]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[Error])(cm.Some[Error](cm.LiftString[Error]((*uint8)(f1), (uint32)(f2))))
}

func lift_CheckedFiles(f0 *string, f1 uint32, f2 *FileError, f3 uint32, f4 *FileError, f5 uint32, f6 uint32, f7 *uint8, f8 uint32) (v CheckedFiles) {
	v.Valid = cm.LiftList[cm.List[string]](f0, f1)
	v.Omitted = cm.LiftList[cm.List[FileError]](f2, f3)
	v.Invalid = cm.LiftList[cm.List[FileError]](f4, f5)
	v.SizeError = lift_OptionError(f6, f7, f8)
	return
}

func lift_FileError(f0 *uint8, f1 uint32, f2 uint32, f3 *uint8, f4 uint32) (v FileError) {
	v.Path = cm.LiftString[string](f0, f1)
	v.Err = lift_OptionError(f2, f3, f4)
	return
}

func lift_UnrecognizedVCSError(f0 *uint8, f1 uint32) (v UnrecognizedVCSError) {
	v.RepoRoot = cm.LiftString[string](f0, f1)
	return
}
