// Code generated by wit-bindgen-go. DO NOT EDIT.

package zip

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "jcbhmr:mod/zip@0.36.0".
var Exports struct {
	// GetMaxZipFile represents the caller-defined, exported function "get-max-zip-file".
	//
	//	get-max-zip-file: func() -> s64
	GetMaxZipFile func() (result int64)

	// GetMaxGoMod represents the caller-defined, exported function "get-max-go-mod".
	//
	//	get-max-go-mod: func() -> s64
	GetMaxGoMod func() (result int64)

	// GetMaxLicense represents the caller-defined, exported function "get-max-license".
	//
	//	get-max-license: func() -> s64
	GetMaxLicense func() (result int64)

	// Create represents the caller-defined, exported function "create".
	//
	//	create: func(w: string, m: version, files: list<file>) -> result<_, error>
	Create func(w string, m Version, files cm.List[File]) (result cm.Result[Error, struct{}, Error])

	// CreateFromDir represents the caller-defined, exported function "create-from-dir".
	//
	//	create-from-dir: func(w: string, m: version, dir: string) -> result<_, error>
	CreateFromDir func(w string, m Version, dir string) (result cm.Result[Error, struct{}, Error])

	// CreateFromVCS represents the caller-defined, exported function "create-from-VCS".
	//
	//	create-from-VCS: func(w: string, m: version, repo-root: string, revision: string,
	//	subdir: string) -> result<_, error>
	CreateFromVCS func(w string, m Version, repoRoot string, revision string, subdir string) (result cm.Result[Error, struct{}, Error])

	// Unzip represents the caller-defined, exported function "unzip".
	//
	//	unzip: func(dir: string, m: version, zip-file: string) -> result<_, error>
	Unzip func(dir string, m Version, zipFile string) (result cm.Result[Error, struct{}, Error])

	// CheckDir represents the caller-defined, exported function "check-dir".
	//
	//	check-dir: func(dir: string) -> tuple<checked-files, option<error>>
	CheckDir func(dir string) (result cm.Tuple[CheckedFiles, cm.Option[Error]])

	// CheckFiles represents the caller-defined, exported function "check-files".
	//
	//	check-files: func(files: list<file>) -> tuple<checked-files, option<error>>
	CheckFiles func(files cm.List[File]) (result cm.Tuple[CheckedFiles, cm.Option[Error]])

	// CheckZip represents the caller-defined, exported function "check-zip".
	//
	//	check-zip: func(m: version, zip-file: string) -> tuple<checked-files, option<error>>
	CheckZip func(m Version, zipFile string) (result cm.Tuple[CheckedFiles, cm.Option[Error]])

	// CheckedFilesErr represents the caller-defined, exported function "checked-files-err".
	//
	//	checked-files-err: func() -> option<error>
	CheckedFilesErr func(self CheckedFiles) (result cm.Option[Error])

	// FileErrorError represents the caller-defined, exported function "file-error-error".
	//
	//	file-error-error: func() -> string
	FileErrorError func(self FileError) (result string)

	// FileErrorUnwrap represents the caller-defined, exported function "file-error-unwrap".
	//
	//	file-error-unwrap: func() -> option<error>
	FileErrorUnwrap func(self FileError) (result cm.Option[Error])

	// FileErrorListError represents the caller-defined, exported function "file-error-list-error".
	//
	//	file-error-list-error: func() -> string
	FileErrorListError func(self FileErrorList) (result string)

	// UnrecognizedVCSErrorError represents the caller-defined, exported function "unrecognized-VCS-error-error".
	//
	//	unrecognized-VCS-error-error: func() -> string
	UnrecognizedVCSErrorError func(self UnrecognizedVCSError) (result string)
}
