// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package zip represents the exported interface "jcbhmr:mod/zip@0.36.0".
package zip

import (
	"go.bytecodealliance.org/cm"
	"go.jcbhmr.com.internal/mod-wasm/internal/jcbhmr/mod/module"
)

// Version represents the type alias "jcbhmr:mod/zip@0.36.0#version".
//
// See [module.Version] for more information.
type Version = module.Version

// Error represents the string "jcbhmr:mod/zip@0.36.0#error".
//
//	type error = string
type Error string

// File represents the string "jcbhmr:mod/zip@0.36.0#file".
//
//	type file = string
type File string

// FileError represents the record "jcbhmr:mod/zip@0.36.0#file-error".
//
//	record file-error {
//		path: string,
//		err: option<error>,
//	}
type FileError struct {
	_    cm.HostLayout    `json:"-"`
	Path string           `json:"path"`
	Err  cm.Option[Error] `json:"err"`
}

// CheckedFiles represents the record "jcbhmr:mod/zip@0.36.0#checked-files".
//
//	record checked-files {
//		valid: list<string>,
//		omitted: list<file-error>,
//		invalid: list<file-error>,
//		size-error: option<error>,
//	}
type CheckedFiles struct {
	_         cm.HostLayout      `json:"-"`
	Valid     cm.List[string]    `json:"valid"`
	Omitted   cm.List[FileError] `json:"omitted"`
	Invalid   cm.List[FileError] `json:"invalid"`
	SizeError cm.Option[Error]   `json:"size-error"`
}

// FileErrorList represents the list "jcbhmr:mod/zip@0.36.0#file-error-list".
//
//	type file-error-list = list<file-error>
type FileErrorList cm.List[FileError]

// UnrecognizedVCSError represents the record "jcbhmr:mod/zip@0.36.0#unrecognized-VCS-error".
//
//	record unrecognized-VCS-error {
//		repo-root: string,
//	}
type UnrecognizedVCSError struct {
	_        cm.HostLayout `json:"-"`
	RepoRoot string        `json:"repo-root"`
}
