// Code generated by wit-bindgen-go. DO NOT EDIT.

package zip

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "jcbhmr:mod@0.36.0".

//go:wasmexport jcbhmr:mod/zip@0.36.0#get-max-zip-file
//export jcbhmr:mod/zip@0.36.0#get-max-zip-file
func wasmexport_GetMaxZipFile() (result0 uint64) {
	result := Exports.GetMaxZipFile()
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#get-max-go-mod
//export jcbhmr:mod/zip@0.36.0#get-max-go-mod
func wasmexport_GetMaxGoMod() (result0 uint64) {
	result := Exports.GetMaxGoMod()
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#get-max-license
//export jcbhmr:mod/zip@0.36.0#get-max-license
func wasmexport_GetMaxLicense() (result0 uint64) {
	result := Exports.GetMaxLicense()
	result0 = (uint64)(result)
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#create
//export jcbhmr:mod/zip@0.36.0#create
func wasmexport_Create(w0 *uint8, w1 uint32, m0 *uint8, m1 uint32, m2 *uint8, m3 uint32, files0 *File, files1 uint32) (result *cm.Result[Error, struct{}, Error]) {
	w := cm.LiftString[string]((*uint8)(w0), (uint32)(w1))
	m := lift_Version((*uint8)(m0), (uint32)(m1), (*uint8)(m2), (uint32)(m3))
	files := cm.LiftList[cm.List[File]]((*File)(files0), (uint32)(files1))
	result_ := Exports.Create(w, m, files)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#create-from-dir
//export jcbhmr:mod/zip@0.36.0#create-from-dir
func wasmexport_CreateFromDir(w0 *uint8, w1 uint32, m0 *uint8, m1 uint32, m2 *uint8, m3 uint32, dir0 *uint8, dir1 uint32) (result *cm.Result[Error, struct{}, Error]) {
	w := cm.LiftString[string]((*uint8)(w0), (uint32)(w1))
	m := lift_Version((*uint8)(m0), (uint32)(m1), (*uint8)(m2), (uint32)(m3))
	dir := cm.LiftString[string]((*uint8)(dir0), (uint32)(dir1))
	result_ := Exports.CreateFromDir(w, m, dir)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#create-from-VCS
//export jcbhmr:mod/zip@0.36.0#create-from-VCS
func wasmexport_CreateFromVCS(w0 *uint8, w1 uint32, m0 *uint8, m1 uint32, m2 *uint8, m3 uint32, repoRoot0 *uint8, repoRoot1 uint32, revision0 *uint8, revision1 uint32, subdir0 *uint8, subdir1 uint32) (result *cm.Result[Error, struct{}, Error]) {
	w := cm.LiftString[string]((*uint8)(w0), (uint32)(w1))
	m := lift_Version((*uint8)(m0), (uint32)(m1), (*uint8)(m2), (uint32)(m3))
	repoRoot := cm.LiftString[string]((*uint8)(repoRoot0), (uint32)(repoRoot1))
	revision := cm.LiftString[string]((*uint8)(revision0), (uint32)(revision1))
	subdir := cm.LiftString[string]((*uint8)(subdir0), (uint32)(subdir1))
	result_ := Exports.CreateFromVCS(w, m, repoRoot, revision, subdir)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#unzip
//export jcbhmr:mod/zip@0.36.0#unzip
func wasmexport_Unzip(dir0 *uint8, dir1 uint32, m0 *uint8, m1 uint32, m2 *uint8, m3 uint32, zipFile0 *uint8, zipFile1 uint32) (result *cm.Result[Error, struct{}, Error]) {
	dir := cm.LiftString[string]((*uint8)(dir0), (uint32)(dir1))
	m := lift_Version((*uint8)(m0), (uint32)(m1), (*uint8)(m2), (uint32)(m3))
	zipFile := cm.LiftString[string]((*uint8)(zipFile0), (uint32)(zipFile1))
	result_ := Exports.Unzip(dir, m, zipFile)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#check-dir
//export jcbhmr:mod/zip@0.36.0#check-dir
func wasmexport_CheckDir(dir0 *uint8, dir1 uint32) (result *cm.Tuple[CheckedFiles, cm.Option[Error]]) {
	dir := cm.LiftString[string]((*uint8)(dir0), (uint32)(dir1))
	result_ := Exports.CheckDir(dir)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#check-files
//export jcbhmr:mod/zip@0.36.0#check-files
func wasmexport_CheckFiles(files0 *File, files1 uint32) (result *cm.Tuple[CheckedFiles, cm.Option[Error]]) {
	files := cm.LiftList[cm.List[File]]((*File)(files0), (uint32)(files1))
	result_ := Exports.CheckFiles(files)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#check-zip
//export jcbhmr:mod/zip@0.36.0#check-zip
func wasmexport_CheckZip(m0 *uint8, m1 uint32, m2 *uint8, m3 uint32, zipFile0 *uint8, zipFile1 uint32) (result *cm.Tuple[CheckedFiles, cm.Option[Error]]) {
	m := lift_Version((*uint8)(m0), (uint32)(m1), (*uint8)(m2), (uint32)(m3))
	zipFile := cm.LiftString[string]((*uint8)(zipFile0), (uint32)(zipFile1))
	result_ := Exports.CheckZip(m, zipFile)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#checked-files-err
//export jcbhmr:mod/zip@0.36.0#checked-files-err
func wasmexport_CheckedFilesErr(self0 *string, self1 uint32, self2 *FileError, self3 uint32, self4 *FileError, self5 uint32, self6 uint32, self7 *uint8, self8 uint32) (result *cm.Option[Error]) {
	self := lift_CheckedFiles((*string)(self0), (uint32)(self1), (*FileError)(self2), (uint32)(self3), (*FileError)(self4), (uint32)(self5), (uint32)(self6), (*uint8)(self7), (uint32)(self8))
	result_ := Exports.CheckedFilesErr(self)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#file-error-error
//export jcbhmr:mod/zip@0.36.0#file-error-error
func wasmexport_FileErrorError(self0 *uint8, self1 uint32, self2 uint32, self3 *uint8, self4 uint32) (result *string) {
	self := lift_FileError((*uint8)(self0), (uint32)(self1), (uint32)(self2), (*uint8)(self3), (uint32)(self4))
	result_ := Exports.FileErrorError(self)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#file-error-unwrap
//export jcbhmr:mod/zip@0.36.0#file-error-unwrap
func wasmexport_FileErrorUnwrap(self0 *uint8, self1 uint32, self2 uint32, self3 *uint8, self4 uint32) (result *cm.Option[Error]) {
	self := lift_FileError((*uint8)(self0), (uint32)(self1), (uint32)(self2), (*uint8)(self3), (uint32)(self4))
	result_ := Exports.FileErrorUnwrap(self)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#file-error-list-error
//export jcbhmr:mod/zip@0.36.0#file-error-list-error
func wasmexport_FileErrorListError(self0 *FileError, self1 uint32) (result *string) {
	self := cm.LiftList[FileErrorList]((*FileError)(self0), (uint32)(self1))
	result_ := Exports.FileErrorListError(self)
	result = &result_
	return
}

//go:wasmexport jcbhmr:mod/zip@0.36.0#unrecognized-VCS-error-error
//export jcbhmr:mod/zip@0.36.0#unrecognized-VCS-error-error
func wasmexport_UnrecognizedVCSErrorError(self0 *uint8, self1 uint32) (result *string) {
	self := lift_UnrecognizedVCSError((*uint8)(self0), (uint32)(self1))
	result_ := Exports.UnrecognizedVCSErrorError(self)
	result = &result_
	return
}
